name: flutter_profile
description: Interfaz del perfil

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/Images/Happy.jpg
     - assets/Images/not_lost.jpg
     - assets/Images/explorer.jpg
     - assets/Images/nature.jpg

  fonts:
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  module:
    androidX: true
    androidPackage: com.example.flutter_profile
    iosBundleIdentifier: com.example.flutterProfile
